export const formInputs = {
  id: 'Identificación',
  name: 'Nombre',
  email: 'Correo Electrónico',
  biographyInformation: 'Información Biográfica',
  firstName: 'Primer Nombre',
  lastName: 'Apellido',
  title: 'Título',
  author: 'Autor',
  description: 'Descripción',
  img: 'Imagen',
  price: 'Precio',
  genere: 'Género',
  language: 'Idioma',
  pageCount: 'Número de Páginas',
  publicationYear: 'Año de Publicación',
  url: 'URL',
  discount: 'Descuento',
  createdAt: 'Creado en',
};
